.PHONY: all check check-format format test lint fix clean test-bazel tidy

all: tidy format test fix

tidy: MODULE.bazel.lock{% if 'go' in languages %} go.sum{% endif %}

MODULE.bazel.lock: MODULE.bazel{% if 'go' in languages %} go.sum{% endif %}
	bazel mod tidy

check: check-format test lint

check-format:
	bazel test //tools/format/...:all

format:
	bazel run //tools/format

test: test-bazel

lint:{% if 'go' in languages %} lint-go{% endif %}{% if 'python' in languages %} lint-python{% endif %}

fix:{% if 'go' in languages %} fix-go{% endif %}{% if 'python' in languages %} fix-python{% endif %}

test-bazel:
	bazel test //...
{% if 'go' in languages %}
# Go lint and fix isn't integrated with bazel yet. Nogo is a good option.
.PHONY: lint-go fix-go

lint-go: go.sum
	golangci-lint run ./...

fix-go: go.sum
	golangci-lint run --fix ./...

go.sum: go.mod
	bazel run @rules_go//go -- mod tidy
{% endif %}
{% if 'python' in languages %}
.PHONY: lint-python fix-python

lint-python:
	ruff check

fix-python:
	ruff check --fix

requirements.txt: requirements.in
	pip-compile --upgrade --output-file=requirements.txt requirements.in
{% endif %}

clean:
	bazel clean --async
